###  Interval.py
###  取得間隔(API用)

from binance.client import Client

# tick interval
m1 = Client.KLINE_INTERVAL_1MINUTE
m3 = Client.KLINE_INTERVAL_3MINUTE
m5 = Client.KLINE_INTERVAL_5MINUTE
m15 = Client.KLINE_INTERVAL_15MINUTE
m30 = Client.KLINE_INTERVAL_30MINUTE
h1 = Client.KLINE_INTERVAL_1HOUR
h2 = Client.KLINE_INTERVAL_2HOUR
h4 = Client.KLINE_INTERVAL_4HOUR
h6 = Client.KLINE_INTERVAL_6HOUR
h8 = Client.KLINE_INTERVAL_8HOUR
h12 = Client.KLINE_INTERVAL_12HOUR
d1 = Client.KLINE_INTERVAL_1DAY
d3 = Client.KLINE_INTERVAL_3DAY
w1 = Client.KLINE_INTERVAL_1WEEK
M1 = Client.KLINE_INTERVAL_1MONTH




